export const BOOK_DESCRIPTIONS: Record<string, string> = {
  "Genesis": "The book of beginnings — creation, the fall, the flood, and the patriarchs Abraham, Isaac, Jacob, and Joseph.",
  "Exodus": "Israel's deliverance from Egyptian slavery, the giving of the Law at Sinai, and the building of the tabernacle.",
  "Leviticus": "Laws and regulations for worship, sacrifice, and holy living given to the priests and people of Israel.",
  "Numbers": "Israel's wilderness wanderings, census records, and preparations to enter the Promised Land.",
  "Deuteronomy": "Moses' farewell speeches to Israel, restating the Law before the people enter Canaan.",
  "Joshua": "The conquest and division of the Promised Land under Joshua's leadership after Moses' death.",
  "Judges": "A cycle of Israel's disobedience, oppression, and deliverance through judges raised by God.",
  "Ruth": "A beautiful story of loyalty and redemption set during the time of the judges, in the lineage of King David.",
  "1 Samuel": "The transition from judges to kings, featuring Samuel the prophet, King Saul, and the rise of David.",
  "2 Samuel": "The reign of King David — his triumphs, failures, and God's covenant promise to his house.",
  "1 Kings": "Solomon's glorious reign, the division of the kingdom, and the ministries of Elijah the prophet.",
  "2 Kings": "The decline and fall of both Israel and Judah, ending in exile, with prophets calling for repentance.",
  "1 Chronicles": "A retelling of Israel's history from Adam through David's reign, emphasizing worship and the temple.",
  "2 Chronicles": "The history of Judah's kings from Solomon to the exile, focusing on faithfulness and temple worship.",
  "Ezra": "The return of Jewish exiles from Babylon and the rebuilding of the temple in Jerusalem.",
  "Nehemiah": "Nehemiah leads the rebuilding of Jerusalem's walls and the spiritual renewal of God's people.",
  "Esther": "A Jewish queen saves her people from destruction in Persia, showing God's hidden providence.",
  "Job": "A righteous man's suffering and his dialogue with friends, concluding with God's sovereign answer.",
  "Psalms": "A collection of 150 songs and prayers expressing the full range of human emotion before God.",
  "Proverbs": "Practical wisdom for daily living — relationships, work, speech, and the fear of the Lord.",
  "Ecclesiastes": "A philosophical exploration of life's meaning, concluding that fearing God is what truly matters.",
  "Song of Solomon": "A poetic celebration of love between a bridegroom and his bride.",
  "Isaiah": "Prophecies of judgment and comfort, including messianic predictions of a coming Servant and King.",
  "Jeremiah": "The weeping prophet's warnings to Judah before the Babylonian exile, with promises of restoration.",
  "Lamentations": "Jeremiah's poetic lament over the destruction of Jerusalem, yet affirming God's faithfulness.",
  "Ezekiel": "Visions and prophecies during the Babylonian exile, pointing to Israel's future restoration.",
  "Daniel": "Stories of faithfulness in exile and apocalyptic visions of God's sovereign plan for history.",
  "Hosea": "God's faithful love illustrated through Hosea's marriage to an unfaithful wife — a picture of Israel.",
  "Joel": "A locust plague prompts a call to repentance and prophecy of God's Spirit being poured out.",
  "Amos": "A shepherd-prophet confronts Israel's social injustice and religious hypocrisy.",
  "Obadiah": "The shortest Old Testament book — a prophecy against Edom for its pride and hostility toward Israel.",
  "Jonah": "A reluctant prophet flees God's call, is swallowed by a great fish, and preaches to Nineveh.",
  "Micah": "Prophecies of judgment and hope, including the famous call to do justly, love mercy, and walk humbly.",
  "Nahum": "A prophecy of Nineveh's destruction, declaring God's power over oppressive nations.",
  "Habakkuk": "A prophet questions God about evil and injustice, ultimately resolving to trust in God's timing.",
  "Zephaniah": "Warnings of the coming Day of the Lord with a promise of restoration for the humble remnant.",
  "Haggai": "A call to the returned exiles to prioritize rebuilding God's temple over personal comforts.",
  "Zechariah": "Visions and prophecies encouraging the post-exile community, with messianic predictions.",
  "Malachi": "The final Old Testament prophet addresses spiritual apathy and points to a coming messenger.",
  "Matthew": "The Gospel presenting Jesus as the promised Messiah and King of Israel, fulfilling Old Testament prophecy.",
  "Mark": "The shortest Gospel, presenting Jesus as the suffering Servant through fast-paced narrative.",
  "Luke": "A careful historical account of Jesus' life emphasizing His compassion for all people.",
  "John": "A theological Gospel focused on Jesus as the divine Son of God, featuring seven signs and discourses.",
  "Acts": "The birth and spread of the early church from Jerusalem to Rome through the power of the Holy Spirit.",
  "Romans": "Paul's systematic explanation of the gospel — sin, salvation, sanctification, and service.",
  "1 Corinthians": "Paul addresses divisions, immorality, and practical questions in the church at Corinth.",
  "2 Corinthians": "Paul defends his apostleship and teaches about strength in weakness and generous giving.",
  "Galatians": "A passionate defense of salvation by grace through faith alone, not by works of the Law.",
  "Ephesians": "The riches of God's grace, the unity of the church, and practical Christian living.",
  "Philippians": "A letter of joy from prison, encouraging contentment and Christ-centered living.",
  "Colossians": "The supremacy and sufficiency of Christ over all philosophies and religious traditions.",
  "1 Thessalonians": "Encouragement to a young church with teaching on holiness and Christ's return.",
  "2 Thessalonians": "Correction about the timing of Christ's return and instruction to live faithfully while waiting.",
  "1 Timothy": "Paul's instructions to a young pastor about church leadership, doctrine, and godly conduct.",
  "2 Timothy": "Paul's final letter — a charge to remain faithful in ministry despite persecution.",
  "Titus": "Guidance for establishing church leadership and promoting good works on the island of Crete.",
  "Philemon": "A personal appeal for the forgiveness and restoration of a runaway slave.",
  "Hebrews": "Christ's superiority over angels, Moses, and the old covenant priesthood and sacrificial system.",
  "James": "Practical wisdom on living out genuine faith through works, speech, and perseverance.",
  "1 Peter": "Encouragement to persecuted believers to stand firm in God's grace and live holy lives.",
  "2 Peter": "Warnings against false teachers and reminders of Christ's promised return.",
  "1 John": "Tests of authentic faith — walking in light, loving others, and believing in Jesus as the Christ.",
  "2 John": "A brief letter warning against false teachers and encouraging faithfulness to truth.",
  "3 John": "A commendation of hospitality and a warning against a domineering church leader.",
  "Jude": "An urgent call to contend for the faith against false teachers infiltrating the church.",
  "Revelation": "Apocalyptic visions of Christ's ultimate victory, judgment of evil, and the new heaven and earth.",
};
