export interface VerseRef {
  book: string;
  chapter: number;
  verse: number;
}

export interface Topic {
  name: string;
  slug: string;
  description: string;
  category: string;
  verses: VerseRef[];
  relatedTopics: string[];
  faq: { question: string; answer: string }[];
}

export type TopicCategory = "Faith & Spirituality" | "Emotions & Character" | "Life & Relationships" | "Difficult & Controversial";

export const TOPIC_CATEGORIES: TopicCategory[] = [
  "Faith & Spirituality",
  "Emotions & Character",
  "Life & Relationships",
  "Difficult & Controversial",
];

export const TOPICS: Topic[] = [
  // ===== FAITH & SPIRITUALITY =====
  {
    name: "Faith",
    slug: "faith",
    description: "Bible verses about faith, believing in God, and trusting His promises.",
    category: "Faith & Spirituality",
    verses: [
      { book: "Hebrews", chapter: 11, verse: 1 },
      { book: "Hebrews", chapter: 11, verse: 6 },
      { book: "Romans", chapter: 10, verse: 17 },
      { book: "2 Corinthians", chapter: 5, verse: 7 },
      { book: "Mark", chapter: 11, verse: 24 },
      { book: "James", chapter: 2, verse: 17 },
      { book: "Matthew", chapter: 17, verse: 20 },
      { book: "Galatians", chapter: 2, verse: 20 },
      { book: "Ephesians", chapter: 2, verse: 8 },
      { book: "Ephesians", chapter: 2, verse: 9 },
      { book: "1 Peter", chapter: 1, verse: 8 },
      { book: "1 Peter", chapter: 1, verse: 9 },
    ],
    relatedTopics: ["trust-in-god", "salvation", "hope", "grace"],
    faq: [
      { question: "What does the Bible say about faith?", answer: "The Bible defines faith as 'the substance of things hoped for, the evidence of things not seen' (Hebrews 11:1). It teaches that faith is essential for pleasing God and is a gift of grace through which believers are saved." },
      { question: "How can I grow my faith according to the Bible?", answer: "Romans 10:17 teaches that faith comes by hearing the word of God. Growing in faith involves reading Scripture, prayer, fellowship with other believers, and trusting God through trials." },
    ],
  },
  {
    name: "Prayer",
    slug: "prayer",
    description: "Scriptures about prayer, how to pray, and God's response to prayer.",
    category: "Faith & Spirituality",
    verses: [
      { book: "Philippians", chapter: 4, verse: 6 },
      { book: "Philippians", chapter: 4, verse: 7 },
      { book: "1 Thessalonians", chapter: 5, verse: 17 },
      { book: "Matthew", chapter: 6, verse: 6 },
      { book: "James", chapter: 5, verse: 16 },
      { book: "Jeremiah", chapter: 29, verse: 12 },
      { book: "Psalms", chapter: 145, verse: 18 },
      { book: "Matthew", chapter: 7, verse: 7 },
      { book: "1 John", chapter: 5, verse: 14 },
      { book: "Romans", chapter: 8, verse: 26 },
      { book: "Mark", chapter: 11, verse: 24 },
      { book: "Luke", chapter: 18, verse: 1 },
    ],
    relatedTopics: ["faith", "worship", "trust-in-god", "holy-spirit"],
    faq: [
      { question: "What does the Bible say about prayer?", answer: "The Bible encourages believers to pray without ceasing (1 Thessalonians 5:17), to bring all concerns to God with thanksgiving (Philippians 4:6), and assures that God hears the prayers of the righteous." },
      { question: "How should Christians pray according to Scripture?", answer: "Jesus taught his disciples to pray privately (Matthew 6:6), with faith (Mark 11:24), and according to God's will (1 John 5:14). He also taught them the Lord's Prayer as a model." },
    ],
  },
  {
    name: "Salvation",
    slug: "salvation",
    description: "Bible verses about being saved, redemption, and eternal life through Christ.",
    category: "Faith & Spirituality",
    verses: [
      { book: "Romans", chapter: 10, verse: 9 },
      { book: "Romans", chapter: 10, verse: 10 },
      { book: "Ephesians", chapter: 2, verse: 8 },
      { book: "Acts", chapter: 4, verse: 12 },
      { book: "John", chapter: 14, verse: 6 },
      { book: "Romans", chapter: 6, verse: 23 },
      { book: "Titus", chapter: 3, verse: 5 },
      { book: "Acts", chapter: 16, verse: 31 },
      { book: "Romans", chapter: 3, verse: 23 },
      { book: "John", chapter: 3, verse: 16 },
      { book: "2 Peter", chapter: 3, verse: 9 },
      { book: "Isaiah", chapter: 45, verse: 22 },
    ],
    relatedTopics: ["grace", "faith", "eternal-life", "repentance"],
    faq: [
      { question: "What does the Bible say about salvation?", answer: "The Bible teaches that salvation is a gift from God received through faith in Jesus Christ (Ephesians 2:8). It declares that all have sinned (Romans 3:23), but God offers forgiveness and eternal life to those who believe." },
      { question: "How is a person saved according to the Bible?", answer: "Romans 10:9 states that confessing Jesus as Lord and believing God raised Him from the dead leads to salvation. It is by grace through faith, not by works (Ephesians 2:8-9)." },
    ],
  },
  {
    name: "Grace",
    slug: "grace",
    description: "Scriptures about God's unmerited favor, mercy, and grace toward sinners.",
    category: "Faith & Spirituality",
    verses: [
      { book: "Ephesians", chapter: 2, verse: 8 },
      { book: "2 Corinthians", chapter: 12, verse: 9 },
      { book: "Romans", chapter: 5, verse: 8 },
      { book: "Titus", chapter: 2, verse: 11 },
      { book: "James", chapter: 4, verse: 6 },
      { book: "Romans", chapter: 3, verse: 24 },
      { book: "2 Timothy", chapter: 1, verse: 9 },
      { book: "Hebrews", chapter: 4, verse: 16 },
      { book: "Romans", chapter: 6, verse: 14 },
      { book: "1 Peter", chapter: 5, verse: 10 },
      { book: "John", chapter: 1, verse: 16 },
      { book: "2 Corinthians", chapter: 9, verse: 8 },
    ],
    relatedTopics: ["salvation", "forgiveness", "gods-love", "mercy"],
    faq: [
      { question: "What is grace in the Bible?", answer: "Grace is God's unmerited favor — His kindness toward people who don't deserve it. Ephesians 2:8 says salvation comes by grace through faith, meaning it is a gift, not earned through human effort." },
      { question: "What Bible verses talk about God's grace?", answer: "Key grace verses include Ephesians 2:8-9, 2 Corinthians 12:9 ('My grace is sufficient for thee'), Romans 5:8, and Titus 2:11 which says grace has appeared to all men." },
    ],
  },
  {
    name: "Holy Spirit",
    slug: "holy-spirit",
    description: "Bible passages about the Holy Spirit, His work, gifts, and presence in believers.",
    category: "Faith & Spirituality",
    verses: [
      { book: "Acts", chapter: 1, verse: 8 },
      { book: "John", chapter: 14, verse: 26 },
      { book: "Romans", chapter: 8, verse: 26 },
      { book: "Galatians", chapter: 5, verse: 22 },
      { book: "Galatians", chapter: 5, verse: 23 },
      { book: "1 Corinthians", chapter: 6, verse: 19 },
      { book: "John", chapter: 16, verse: 13 },
      { book: "Ephesians", chapter: 4, verse: 30 },
      { book: "Acts", chapter: 2, verse: 4 },
      { book: "Romans", chapter: 8, verse: 14 },
      { book: "2 Timothy", chapter: 1, verse: 7 },
      { book: "Ephesians", chapter: 1, verse: 13 },
    ],
    relatedTopics: ["spiritual-growth", "faith", "worship", "prayer"],
    faq: [
      { question: "What does the Bible say about the Holy Spirit?", answer: "The Bible teaches that the Holy Spirit is the third person of the Trinity who indwells believers (1 Corinthians 6:19), guides them into truth (John 16:13), and empowers them for service (Acts 1:8)." },
      { question: "What are the fruits of the Holy Spirit?", answer: "Galatians 5:22-23 lists the fruit of the Spirit: love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, and temperance." },
    ],
  },
  {
    name: "Worship",
    slug: "worship",
    description: "Verses about praising God, corporate worship, and living a life of worship.",
    category: "Faith & Spirituality",
    verses: [
      { book: "John", chapter: 4, verse: 24 },
      { book: "Psalms", chapter: 95, verse: 6 },
      { book: "Romans", chapter: 12, verse: 1 },
      { book: "Psalms", chapter: 100, verse: 2 },
      { book: "Hebrews", chapter: 13, verse: 15 },
      { book: "Psalms", chapter: 150, verse: 6 },
      { book: "1 Chronicles", chapter: 16, verse: 29 },
      { book: "Psalms", chapter: 29, verse: 2 },
      { book: "Colossians", chapter: 3, verse: 16 },
      { book: "Psalms", chapter: 96, verse: 9 },
      { book: "Revelation", chapter: 4, verse: 11 },
      { book: "Psalms", chapter: 63, verse: 3 },
    ],
    relatedTopics: ["prayer", "gratitude", "joy", "holy-spirit"],
    faq: [
      { question: "What does the Bible say about worship?", answer: "Jesus said God must be worshipped 'in spirit and in truth' (John 4:24). The Bible teaches that worship involves praise, prayer, song, giving, and living a life devoted to God (Romans 12:1)." },
      { question: "Why is worship important in Christianity?", answer: "Worship acknowledges God's worthiness and sovereignty. The Psalms repeatedly call believers to praise God. Revelation 4:11 says God is worthy because He created all things." },
    ],
  },
  {
    name: "Repentance",
    slug: "repentance",
    description: "Scriptures about turning from sin, God's call to repent, and spiritual renewal.",
    category: "Faith & Spirituality",
    verses: [
      { book: "Acts", chapter: 3, verse: 19 },
      { book: "2 Chronicles", chapter: 7, verse: 14 },
      { book: "Acts", chapter: 17, verse: 30 },
      { book: "Luke", chapter: 15, verse: 7 },
      { book: "2 Peter", chapter: 3, verse: 9 },
      { book: "Isaiah", chapter: 55, verse: 7 },
      { book: "Ezekiel", chapter: 18, verse: 30 },
      { book: "Joel", chapter: 2, verse: 12 },
      { book: "Mark", chapter: 1, verse: 15 },
      { book: "Romans", chapter: 2, verse: 4 },
      { book: "Revelation", chapter: 3, verse: 19 },
      { book: "Psalms", chapter: 51, verse: 10 },
    ],
    relatedTopics: ["forgiveness", "salvation", "grace", "spiritual-growth"],
    faq: [
      { question: "What is repentance according to the Bible?", answer: "Repentance means a genuine change of heart and mind that leads to turning away from sin and toward God. Acts 3:19 calls believers to 'repent and be converted, that your sins may be blotted out.'" },
      { question: "Why does God call us to repent?", answer: "God desires that none perish (2 Peter 3:9) and calls all to repentance out of His goodness and love (Romans 2:4). Jesus began His ministry proclaiming 'Repent: for the kingdom of heaven is at hand' (Mark 1:15)." },
    ],
  },
  {
    name: "Baptism",
    slug: "baptism",
    description: "Bible verses about baptism, its meaning, and its significance for believers.",
    category: "Faith & Spirituality",
    verses: [
      { book: "Matthew", chapter: 28, verse: 19 },
      { book: "Acts", chapter: 2, verse: 38 },
      { book: "Romans", chapter: 6, verse: 4 },
      { book: "Mark", chapter: 16, verse: 16 },
      { book: "1 Peter", chapter: 3, verse: 21 },
      { book: "Galatians", chapter: 3, verse: 27 },
      { book: "Acts", chapter: 22, verse: 16 },
      { book: "Colossians", chapter: 2, verse: 12 },
      { book: "Ephesians", chapter: 4, verse: 5 },
      { book: "Matthew", chapter: 3, verse: 16 },
      { book: "Acts", chapter: 8, verse: 36 },
      { book: "Acts", chapter: 8, verse: 38 },
    ],
    relatedTopics: ["salvation", "repentance", "faith", "holy-spirit"],
    faq: [
      { question: "What does the Bible say about baptism?", answer: "The Bible presents baptism as an outward expression of an inward faith. Jesus commanded His followers to baptize in Matthew 28:19, and Acts 2:38 connects it with repentance and the forgiveness of sins." },
      { question: "Is baptism necessary for salvation?", answer: "Christians have varying views on this. Mark 16:16 and Acts 2:38 link baptism with salvation, while Ephesians 2:8-9 emphasizes salvation by grace through faith. Most agree baptism is an act of obedience following conversion." },
    ],
  },
  {
    name: "Heaven",
    slug: "heaven",
    description: "Verses about heaven, the afterlife, and the eternal home promised to believers.",
    category: "Faith & Spirituality",
    verses: [
      { book: "John", chapter: 14, verse: 2 },
      { book: "John", chapter: 14, verse: 3 },
      { book: "Revelation", chapter: 21, verse: 4 },
      { book: "Philippians", chapter: 3, verse: 20 },
      { book: "2 Corinthians", chapter: 5, verse: 1 },
      { book: "1 Peter", chapter: 1, verse: 4 },
      { book: "Revelation", chapter: 21, verse: 21 },
      { book: "Matthew", chapter: 6, verse: 20 },
      { book: "Colossians", chapter: 3, verse: 2 },
      { book: "1 Thessalonians", chapter: 4, verse: 17 },
      { book: "Revelation", chapter: 22, verse: 5 },
      { book: "Isaiah", chapter: 65, verse: 17 },
    ],
    relatedTopics: ["eternal-life", "death", "hope", "salvation"],
    faq: [
      { question: "What does the Bible say heaven is like?", answer: "Revelation 21:4 says there will be no death, sorrow, crying, or pain. Jesus said He prepares a place for believers (John 14:2-3). It is described as a place of glory, light, and God's presence." },
      { question: "Who goes to heaven according to the Bible?", answer: "The Bible teaches that heaven is for those who put their faith in Jesus Christ. John 14:6 says Jesus is 'the way, the truth, and the life' and no one comes to the Father except through Him." },
    ],
  },
  {
    name: "Eternal Life",
    slug: "eternal-life",
    description: "Scriptures about eternal life, living forever with God, and the promise of immortality.",
    category: "Faith & Spirituality",
    verses: [
      { book: "John", chapter: 3, verse: 16 },
      { book: "John", chapter: 10, verse: 28 },
      { book: "Romans", chapter: 6, verse: 23 },
      { book: "1 John", chapter: 5, verse: 11 },
      { book: "1 John", chapter: 5, verse: 13 },
      { book: "John", chapter: 17, verse: 3 },
      { book: "John", chapter: 5, verse: 24 },
      { book: "Titus", chapter: 1, verse: 2 },
      { book: "Matthew", chapter: 25, verse: 46 },
      { book: "John", chapter: 6, verse: 47 },
      { book: "1 John", chapter: 2, verse: 25 },
      { book: "Daniel", chapter: 12, verse: 2 },
    ],
    relatedTopics: ["heaven", "salvation", "faith", "hope"],
    faq: [
      { question: "What does the Bible say about eternal life?", answer: "John 3:16 declares that whoever believes in God's Son shall not perish but have everlasting life. Eternal life is described as knowing God and Jesus Christ (John 17:3) and is a gift, not earned (Romans 6:23)." },
      { question: "Can a person have assurance of eternal life?", answer: "1 John 5:13 says these things are written 'that ye may know that ye have eternal life.' John 10:28 promises that believers shall never perish and no one can pluck them from God's hand." },
    ],
  },
  {
    name: "God's Love",
    slug: "gods-love",
    description: "Bible verses about God's unconditional love for humanity and His children.",
    category: "Faith & Spirituality",
    verses: [
      { book: "Romans", chapter: 5, verse: 8 },
      { book: "1 John", chapter: 4, verse: 9 },
      { book: "1 John", chapter: 4, verse: 10 },
      { book: "John", chapter: 3, verse: 16 },
      { book: "Romans", chapter: 8, verse: 38 },
      { book: "Romans", chapter: 8, verse: 39 },
      { book: "Ephesians", chapter: 2, verse: 4 },
      { book: "Ephesians", chapter: 2, verse: 5 },
      { book: "Psalms", chapter: 86, verse: 15 },
      { book: "Zephaniah", chapter: 3, verse: 17 },
      { book: "Jeremiah", chapter: 31, verse: 3 },
      { book: "1 John", chapter: 3, verse: 1 },
    ],
    relatedTopics: ["love", "grace", "compassion", "forgiveness"],
    faq: [
      { question: "How does the Bible describe God's love?", answer: "Romans 5:8 says God demonstrated His love by sending Christ to die while we were still sinners. 1 John 4:8 declares 'God is love.' His love is described as everlasting (Jeremiah 31:3) and inseparable from believers (Romans 8:38-39)." },
      { question: "What is the greatest expression of God's love?", answer: "John 3:16 says God 'so loved the world, that he gave his only begotten Son' — the sacrifice of Jesus Christ is presented as the supreme demonstration of divine love." },
    ],
  },
  {
    name: "Trust in God",
    slug: "trust-in-god",
    description: "Verses about trusting God in all circumstances, relying on His plan and provision.",
    category: "Faith & Spirituality",
    verses: [
      { book: "Proverbs", chapter: 3, verse: 5 },
      { book: "Proverbs", chapter: 3, verse: 6 },
      { book: "Psalms", chapter: 37, verse: 5 },
      { book: "Isaiah", chapter: 26, verse: 3 },
      { book: "Jeremiah", chapter: 17, verse: 7 },
      { book: "Psalms", chapter: 56, verse: 3 },
      { book: "Nahum", chapter: 1, verse: 7 },
      { book: "Psalms", chapter: 9, verse: 10 },
      { book: "Psalms", chapter: 125, verse: 1 },
      { book: "Psalms", chapter: 62, verse: 8 },
      { book: "Proverbs", chapter: 29, verse: 25 },
      { book: "Isaiah", chapter: 41, verse: 10 },
    ],
    relatedTopics: ["faith", "hope", "peace", "courage"],
    faq: [
      { question: "What does the Bible say about trusting God?", answer: "Proverbs 3:5-6 instructs believers to 'trust in the LORD with all thine heart; and lean not unto thine own understanding.' The Bible promises that those who trust God will find peace (Isaiah 26:3) and strength." },
      { question: "How can I trust God during difficult times?", answer: "Psalm 56:3 says 'What time I am afraid, I will trust in thee.' Scripture encourages believers to remember God's faithfulness, rely on His promises, and cast their cares upon Him (1 Peter 5:7)." },
    ],
  },
  {
    name: "Spiritual Growth",
    slug: "spiritual-growth",
    description: "Scriptures about growing in faith, maturing spiritually, and becoming more Christlike.",
    category: "Faith & Spirituality",
    verses: [
      { book: "2 Peter", chapter: 3, verse: 18 },
      { book: "Philippians", chapter: 1, verse: 6 },
      { book: "Colossians", chapter: 1, verse: 10 },
      { book: "Hebrews", chapter: 5, verse: 14 },
      { book: "Ephesians", chapter: 4, verse: 15 },
      { book: "1 Peter", chapter: 2, verse: 2 },
      { book: "Galatians", chapter: 5, verse: 22 },
      { book: "Romans", chapter: 12, verse: 2 },
      { book: "2 Corinthians", chapter: 3, verse: 18 },
      { book: "James", chapter: 1, verse: 4 },
      { book: "Philippians", chapter: 3, verse: 14 },
      { book: "2 Timothy", chapter: 3, verse: 16 },
    ],
    relatedTopics: ["faith", "holy-spirit", "wisdom", "patience"],
    faq: [
      { question: "How does a Christian grow spiritually?", answer: "The Bible teaches spiritual growth comes through Scripture study (2 Timothy 3:16), prayer, fellowship, obedience, and the work of the Holy Spirit. 1 Peter 2:2 says to 'desire the sincere milk of the word, that ye may grow thereby.'" },
      { question: "What does spiritual maturity look like biblically?", answer: "Hebrews 5:14 describes the mature as those trained to discern good and evil. The fruit of the Spirit (Galatians 5:22-23) and being transformed by renewing the mind (Romans 12:2) are marks of growth." },
    ],
  },

  // ===== EMOTIONS & CHARACTER =====
  {
    name: "Love",
    slug: "love",
    description: "Bible verses about love — God's love, loving others, and the nature of true love.",
    category: "Emotions & Character",
    verses: [
      { book: "1 Corinthians", chapter: 13, verse: 4 },
      { book: "1 Corinthians", chapter: 13, verse: 5 },
      { book: "1 Corinthians", chapter: 13, verse: 6 },
      { book: "1 Corinthians", chapter: 13, verse: 7 },
      { book: "John", chapter: 3, verse: 16 },
      { book: "Romans", chapter: 8, verse: 38 },
      { book: "Romans", chapter: 8, verse: 39 },
      { book: "1 John", chapter: 4, verse: 8 },
      { book: "1 John", chapter: 4, verse: 19 },
      { book: "Song of Solomon", chapter: 8, verse: 6 },
      { book: "Song of Solomon", chapter: 8, verse: 7 },
      { book: "Proverbs", chapter: 10, verse: 12 },
      { book: "Romans", chapter: 13, verse: 10 },
      { book: "Galatians", chapter: 5, verse: 22 },
      { book: "1 Peter", chapter: 4, verse: 8 },
    ],
    relatedTopics: ["gods-love", "marriage", "kindness", "compassion"],
    faq: [
      { question: "What does the Bible say about love?", answer: "The Bible describes love as patient, kind, not envious, not boastful (1 Corinthians 13:4-7). It says God is love (1 John 4:8) and the greatest commandment is to love God and love others (Matthew 22:37-39)." },
      { question: "What is the most famous Bible verse about love?", answer: "John 3:16 is widely considered the most famous verse about love: 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.'" },
    ],
  },
  {
    name: "Hope",
    slug: "hope",
    description: "Scriptures about hope in God, hope for the future, and hope in difficult times.",
    category: "Emotions & Character",
    verses: [
      { book: "Romans", chapter: 15, verse: 13 },
      { book: "Jeremiah", chapter: 29, verse: 11 },
      { book: "Hebrews", chapter: 11, verse: 1 },
      { book: "Romans", chapter: 8, verse: 24 },
      { book: "Romans", chapter: 8, verse: 25 },
      { book: "Psalms", chapter: 39, verse: 7 },
      { book: "Psalms", chapter: 71, verse: 5 },
      { book: "Isaiah", chapter: 40, verse: 31 },
      { book: "Lamentations", chapter: 3, verse: 24 },
      { book: "1 Peter", chapter: 1, verse: 3 },
      { book: "Psalms", chapter: 42, verse: 11 },
      { book: "Romans", chapter: 5, verse: 5 },
    ],
    relatedTopics: ["faith", "trust-in-god", "comfort", "peace"],
    faq: [
      { question: "What does the Bible say about hope?", answer: "Romans 15:13 calls God 'the God of hope' who fills believers with joy and peace. Jeremiah 29:11 promises plans for a future and hope. Biblical hope is confident expectation grounded in God's character." },
      { question: "How can I find hope when life is hard?", answer: "Isaiah 40:31 promises that those who wait upon the Lord shall renew their strength. Lamentations 3:24 declares the Lord is our portion, therefore we will hope in Him. Hope comes from trusting God's promises." },
    ],
  },
  {
    name: "Peace",
    slug: "peace",
    description: "Bible verses about peace of mind, peace with God, and being a peacemaker.",
    category: "Emotions & Character",
    verses: [
      { book: "John", chapter: 14, verse: 27 },
      { book: "Philippians", chapter: 4, verse: 7 },
      { book: "Isaiah", chapter: 26, verse: 3 },
      { book: "Romans", chapter: 5, verse: 1 },
      { book: "Colossians", chapter: 3, verse: 15 },
      { book: "Psalms", chapter: 29, verse: 11 },
      { book: "2 Thessalonians", chapter: 3, verse: 16 },
      { book: "Numbers", chapter: 6, verse: 26 },
      { book: "Romans", chapter: 8, verse: 6 },
      { book: "Psalms", chapter: 34, verse: 14 },
      { book: "Matthew", chapter: 5, verse: 9 },
      { book: "Isaiah", chapter: 9, verse: 6 },
    ],
    relatedTopics: ["anxiety", "trust-in-god", "joy", "comfort"],
    faq: [
      { question: "What does the Bible say about peace?", answer: "Jesus said 'Peace I leave with you, my peace I give unto you' (John 14:27). The Bible promises a peace that surpasses understanding (Philippians 4:7) and calls believers to pursue peace with others." },
      { question: "How can I have peace according to the Bible?", answer: "Isaiah 26:3 says God keeps in perfect peace those whose minds are stayed on Him. Peace comes through faith (Romans 5:1), prayer (Philippians 4:6-7), and trusting God's sovereignty." },
    ],
  },
  {
    name: "Joy",
    slug: "joy",
    description: "Verses about joy in the Lord, rejoicing in all circumstances, and the joy of salvation.",
    category: "Emotions & Character",
    verses: [
      { book: "Nehemiah", chapter: 8, verse: 10 },
      { book: "Psalms", chapter: 16, verse: 11 },
      { book: "Romans", chapter: 15, verse: 13 },
      { book: "John", chapter: 15, verse: 11 },
      { book: "Galatians", chapter: 5, verse: 22 },
      { book: "Philippians", chapter: 4, verse: 4 },
      { book: "James", chapter: 1, verse: 2 },
      { book: "Psalms", chapter: 30, verse: 5 },
      { book: "1 Peter", chapter: 1, verse: 8 },
      { book: "Habakkuk", chapter: 3, verse: 18 },
      { book: "Isaiah", chapter: 61, verse: 10 },
      { book: "Psalms", chapter: 118, verse: 24 },
    ],
    relatedTopics: ["peace", "gratitude", "worship", "hope"],
    faq: [
      { question: "What does the Bible say about joy?", answer: "The Bible distinguishes joy from happiness — joy is a fruit of the Spirit (Galatians 5:22) that persists regardless of circumstances. Nehemiah 8:10 says 'the joy of the LORD is your strength.'" },
      { question: "How can Christians be joyful during trials?", answer: "James 1:2 says to 'count it all joy when ye fall into divers temptations' because testing produces patience. Joy comes from relationship with God, not from circumstances (Habakkuk 3:18)." },
    ],
  },
  {
    name: "Patience",
    slug: "patience",
    description: "Scriptures about patience, waiting on God, and enduring with a steadfast spirit.",
    category: "Emotions & Character",
    verses: [
      { book: "James", chapter: 1, verse: 3 },
      { book: "James", chapter: 1, verse: 4 },
      { book: "Romans", chapter: 12, verse: 12 },
      { book: "Galatians", chapter: 6, verse: 9 },
      { book: "Hebrews", chapter: 10, verse: 36 },
      { book: "Psalms", chapter: 37, verse: 7 },
      { book: "Proverbs", chapter: 14, verse: 29 },
      { book: "Ecclesiastes", chapter: 7, verse: 8 },
      { book: "Colossians", chapter: 3, verse: 12 },
      { book: "2 Peter", chapter: 3, verse: 9 },
      { book: "Romans", chapter: 8, verse: 25 },
      { book: "Isaiah", chapter: 40, verse: 31 },
    ],
    relatedTopics: ["faith", "hope", "perseverance", "peace"],
    faq: [
      { question: "What does the Bible teach about patience?", answer: "The Bible teaches that patience (longsuffering) is a fruit of the Spirit (Galatians 5:22). James 1:3-4 says the testing of faith produces patience, and patience leads to spiritual completeness." },
      { question: "How can I develop more patience according to Scripture?", answer: "Patience develops through trials (Romans 5:3-4), by waiting on God (Psalm 37:7), and through the power of the Holy Spirit. Hebrews 10:36 reminds us that patience is needed to receive God's promises." },
    ],
  },
  {
    name: "Courage",
    slug: "courage",
    description: "Bible verses about courage, boldness, and overcoming fear through faith in God.",
    category: "Emotions & Character",
    verses: [
      { book: "Joshua", chapter: 1, verse: 9 },
      { book: "Deuteronomy", chapter: 31, verse: 6 },
      { book: "Isaiah", chapter: 41, verse: 10 },
      { book: "Psalms", chapter: 27, verse: 1 },
      { book: "2 Timothy", chapter: 1, verse: 7 },
      { book: "1 Corinthians", chapter: 16, verse: 13 },
      { book: "Psalms", chapter: 31, verse: 24 },
      { book: "Proverbs", chapter: 28, verse: 1 },
      { book: "Deuteronomy", chapter: 31, verse: 8 },
      { book: "Isaiah", chapter: 43, verse: 1 },
      { book: "Psalms", chapter: 56, verse: 3 },
      { book: "Philippians", chapter: 4, verse: 13 },
    ],
    relatedTopics: ["faith", "fear", "strength", "trust-in-god"],
    faq: [
      { question: "What does the Bible say about courage?", answer: "God repeatedly tells His people to 'be strong and of a good courage' (Joshua 1:9). Biblical courage is not the absence of fear but confidence in God's presence. 2 Timothy 1:7 says God gives a spirit of power, not fear." },
      { question: "Where does courage come from according to Scripture?", answer: "Courage comes from knowing God is with us (Deuteronomy 31:6), trusting His power (Isaiah 41:10), and knowing He is our light and salvation (Psalm 27:1). It is faith applied to fearful situations." },
    ],
  },
  {
    name: "Strength",
    slug: "strength",
    description: "Verses about finding strength in God, spiritual and physical strength from the Lord.",
    category: "Emotions & Character",
    verses: [
      { book: "Philippians", chapter: 4, verse: 13 },
      { book: "Isaiah", chapter: 40, verse: 31 },
      { book: "Psalms", chapter: 46, verse: 1 },
      { book: "2 Corinthians", chapter: 12, verse: 9 },
      { book: "Ephesians", chapter: 6, verse: 10 },
      { book: "Psalms", chapter: 28, verse: 7 },
      { book: "Isaiah", chapter: 41, verse: 10 },
      { book: "Nehemiah", chapter: 8, verse: 10 },
      { book: "Habakkuk", chapter: 3, verse: 19 },
      { book: "Psalms", chapter: 73, verse: 26 },
      { book: "2 Samuel", chapter: 22, verse: 33 },
      { book: "Deuteronomy", chapter: 33, verse: 25 },
    ],
    relatedTopics: ["courage", "faith", "hope", "trust-in-god"],
    faq: [
      { question: "What does the Bible say about strength?", answer: "The Bible teaches that true strength comes from God. Philippians 4:13 says 'I can do all things through Christ which strengtheneth me.' Isaiah 40:31 promises renewed strength for those who wait upon the Lord." },
      { question: "How can I find strength in difficult times?", answer: "2 Corinthians 12:9 says God's strength is made perfect in weakness. Psalm 46:1 declares God is 'a very present help in trouble.' Believers find strength through prayer, Scripture, and reliance on God." },
    ],
  },
  {
    name: "Comfort",
    slug: "comfort",
    description: "Scriptures about God's comfort in times of grief, loss, pain, and sorrow.",
    category: "Emotions & Character",
    verses: [
      { book: "2 Corinthians", chapter: 1, verse: 3 },
      { book: "2 Corinthians", chapter: 1, verse: 4 },
      { book: "Psalms", chapter: 23, verse: 4 },
      { book: "Matthew", chapter: 5, verse: 4 },
      { book: "Psalms", chapter: 34, verse: 18 },
      { book: "Isaiah", chapter: 51, verse: 12 },
      { book: "John", chapter: 14, verse: 16 },
      { book: "Romans", chapter: 8, verse: 28 },
      { book: "Psalms", chapter: 119, verse: 50 },
      { book: "Psalms", chapter: 46, verse: 1 },
      { book: "Isaiah", chapter: 66, verse: 13 },
      { book: "Revelation", chapter: 21, verse: 4 },
    ],
    relatedTopics: ["grief", "hope", "peace", "gods-love"],
    faq: [
      { question: "What does the Bible say about comfort?", answer: "2 Corinthians 1:3-4 calls God 'the God of all comfort, who comforteth us in all our tribulation.' Jesus promised the Holy Spirit as a Comforter (John 14:16). God is near to the brokenhearted (Psalm 34:18)." },
      { question: "Where can I find comfort in the Bible?", answer: "Psalm 23 is the most beloved comfort passage. Matthew 5:4 promises 'Blessed are they that mourn: for they shall be comforted.' Romans 8:28 assures that God works all things for good." },
    ],
  },
  {
    name: "Gratitude",
    slug: "gratitude",
    description: "Bible verses about thankfulness, giving thanks to God, and a grateful heart.",
    category: "Emotions & Character",
    verses: [
      { book: "1 Thessalonians", chapter: 5, verse: 18 },
      { book: "Psalms", chapter: 107, verse: 1 },
      { book: "Colossians", chapter: 3, verse: 17 },
      { book: "Philippians", chapter: 4, verse: 6 },
      { book: "Psalms", chapter: 100, verse: 4 },
      { book: "Ephesians", chapter: 5, verse: 20 },
      { book: "Psalms", chapter: 9, verse: 1 },
      { book: "James", chapter: 1, verse: 17 },
      { book: "1 Chronicles", chapter: 16, verse: 34 },
      { book: "Psalms", chapter: 136, verse: 1 },
      { book: "Psalms", chapter: 118, verse: 1 },
      { book: "Colossians", chapter: 2, verse: 7 },
    ],
    relatedTopics: ["joy", "worship", "prayer", "peace"],
    faq: [
      { question: "What does the Bible say about gratitude?", answer: "1 Thessalonians 5:18 says 'In every thing give thanks: for this is the will of God.' The Psalms overflow with thanksgiving to God. Gratitude is both a command and a response to God's goodness." },
      { question: "Why is thankfulness important in Christianity?", answer: "Thankfulness shifts focus from problems to God's provision. Colossians 3:17 says to do everything with thanks. A grateful heart acknowledges God as the source of every good gift (James 1:17)." },
    ],
  },
  {
    name: "Humility",
    slug: "humility",
    description: "Verses about humility, putting others first, and the meekness Christ modeled.",
    category: "Emotions & Character",
    verses: [
      { book: "Philippians", chapter: 2, verse: 3 },
      { book: "James", chapter: 4, verse: 10 },
      { book: "Proverbs", chapter: 11, verse: 2 },
      { book: "1 Peter", chapter: 5, verse: 6 },
      { book: "Micah", chapter: 6, verse: 8 },
      { book: "Colossians", chapter: 3, verse: 12 },
      { book: "Proverbs", chapter: 22, verse: 4 },
      { book: "Matthew", chapter: 23, verse: 12 },
      { book: "James", chapter: 4, verse: 6 },
      { book: "Ephesians", chapter: 4, verse: 2 },
      { book: "Psalms", chapter: 25, verse: 9 },
      { book: "Proverbs", chapter: 16, verse: 19 },
    ],
    relatedTopics: ["kindness", "wisdom", "spiritual-growth", "love"],
    faq: [
      { question: "What does the Bible say about humility?", answer: "The Bible presents humility as essential. Philippians 2:3 says to esteem others better than yourself. James 4:10 promises that those who humble themselves before God will be lifted up." },
      { question: "Why is humility important to God?", answer: "Micah 6:8 lists walking humbly with God as one of His requirements. Proverbs 11:2 says 'with the lowly is wisdom.' Jesus modeled humility and taught that the greatest must be the servant of all." },
    ],
  },
  {
    name: "Wisdom",
    slug: "wisdom",
    description: "Scriptures about wisdom, seeking understanding, and godly discernment.",
    category: "Emotions & Character",
    verses: [
      { book: "Proverbs", chapter: 1, verse: 7 },
      { book: "James", chapter: 1, verse: 5 },
      { book: "Proverbs", chapter: 3, verse: 5 },
      { book: "Proverbs", chapter: 3, verse: 6 },
      { book: "Proverbs", chapter: 4, verse: 7 },
      { book: "Colossians", chapter: 3, verse: 16 },
      { book: "Proverbs", chapter: 9, verse: 10 },
      { book: "Ecclesiastes", chapter: 7, verse: 12 },
      { book: "Psalms", chapter: 111, verse: 10 },
      { book: "Proverbs", chapter: 2, verse: 6 },
      { book: "Proverbs", chapter: 16, verse: 16 },
      { book: "Daniel", chapter: 2, verse: 21 },
    ],
    relatedTopics: ["faith", "spiritual-growth", "humility", "trust-in-god"],
    faq: [
      { question: "What does the Bible say about wisdom?", answer: "Proverbs 1:7 says 'The fear of the LORD is the beginning of knowledge.' James 1:5 promises that God gives wisdom generously to those who ask. True wisdom begins with reverence for God." },
      { question: "How can I gain wisdom according to the Bible?", answer: "Ask God (James 1:5), fear the Lord (Proverbs 9:10), study Scripture (2 Timothy 3:15-16), and seek counsel from the wise (Proverbs 13:20). Wisdom is more valuable than gold (Proverbs 16:16)." },
    ],
  },
  {
    name: "Kindness",
    slug: "kindness",
    description: "Bible verses about kindness, being generous in spirit, and treating others well.",
    category: "Emotions & Character",
    verses: [
      { book: "Ephesians", chapter: 4, verse: 32 },
      { book: "Colossians", chapter: 3, verse: 12 },
      { book: "Proverbs", chapter: 11, verse: 17 },
      { book: "Galatians", chapter: 5, verse: 22 },
      { book: "Luke", chapter: 6, verse: 35 },
      { book: "Proverbs", chapter: 19, verse: 22 },
      { book: "Micah", chapter: 6, verse: 8 },
      { book: "1 Corinthians", chapter: 13, verse: 4 },
      { book: "Romans", chapter: 2, verse: 4 },
      { book: "Proverbs", chapter: 31, verse: 26 },
      { book: "2 Peter", chapter: 1, verse: 7 },
      { book: "Titus", chapter: 3, verse: 4 },
    ],
    relatedTopics: ["love", "compassion", "generosity", "humility"],
    faq: [
      { question: "What does the Bible say about kindness?", answer: "Ephesians 4:32 says 'be ye kind one to another, tenderhearted, forgiving one another.' Kindness is listed as a fruit of the Spirit (Galatians 5:22) and is described as a quality of true love (1 Corinthians 13:4)." },
      { question: "Why does God value kindness?", answer: "Romans 2:4 says God's kindness leads to repentance — He models kindness for us. Micah 6:8 lists loving kindness as one of three things God requires. Even small acts of kindness reflect God's character." },
    ],
  },
  {
    name: "Forgiveness",
    slug: "forgiveness",
    description: "Scriptures about forgiving others, receiving God's forgiveness, and letting go of bitterness.",
    category: "Emotions & Character",
    verses: [
      { book: "Matthew", chapter: 6, verse: 14 },
      { book: "Matthew", chapter: 6, verse: 15 },
      { book: "Ephesians", chapter: 4, verse: 32 },
      { book: "Colossians", chapter: 3, verse: 13 },
      { book: "Mark", chapter: 11, verse: 25 },
      { book: "Luke", chapter: 6, verse: 37 },
      { book: "Psalms", chapter: 103, verse: 12 },
      { book: "Isaiah", chapter: 1, verse: 18 },
      { book: "1 John", chapter: 1, verse: 9 },
      { book: "Micah", chapter: 7, verse: 18 },
      { book: "Micah", chapter: 7, verse: 19 },
      { book: "Acts", chapter: 3, verse: 19 },
    ],
    relatedTopics: ["grace", "love", "repentance", "compassion"],
    faq: [
      { question: "What does the Bible say about forgiveness?", answer: "Jesus taught that we must forgive others to receive God's forgiveness (Matthew 6:14-15). 1 John 1:9 promises that God is faithful to forgive sins when we confess them. Forgiveness is a central teaching of Christianity." },
      { question: "How many times should I forgive someone?", answer: "Jesus told Peter to forgive 'seventy times seven' (Matthew 18:22), meaning without limit. Colossians 3:13 says to forgive as Christ forgave us. Biblical forgiveness is not optional for believers." },
    ],
  },
  {
    name: "Compassion",
    slug: "compassion",
    description: "Verses about compassion, mercy, and caring for those who are hurting.",
    category: "Emotions & Character",
    verses: [
      { book: "Colossians", chapter: 3, verse: 12 },
      { book: "Psalms", chapter: 145, verse: 9 },
      { book: "Lamentations", chapter: 3, verse: 22 },
      { book: "Lamentations", chapter: 3, verse: 23 },
      { book: "Matthew", chapter: 9, verse: 36 },
      { book: "1 Peter", chapter: 3, verse: 8 },
      { book: "Isaiah", chapter: 49, verse: 13 },
      { book: "Psalms", chapter: 86, verse: 15 },
      { book: "Zechariah", chapter: 7, verse: 9 },
      { book: "2 Corinthians", chapter: 1, verse: 3 },
      { book: "Ephesians", chapter: 4, verse: 32 },
      { book: "Exodus", chapter: 34, verse: 6 },
    ],
    relatedTopics: ["kindness", "love", "mercy", "gods-love"],
    faq: [
      { question: "What does the Bible say about compassion?", answer: "The Bible describes God as 'full of compassion' (Psalm 86:15) and commands believers to put on 'bowels of mercies, kindness, humbleness of mind' (Colossians 3:12). Jesus was moved with compassion toward the crowds (Matthew 9:36)." },
      { question: "How should Christians show compassion?", answer: "1 Peter 3:8 says to have compassion one of another. Zechariah 7:9 commands showing mercy and compassion to others. Christians demonstrate compassion through acts of service, mercy, and caring for the needy." },
    ],
  },

  // ===== LIFE & RELATIONSHIPS =====
  {
    name: "Marriage",
    slug: "marriage",
    description: "Bible verses about marriage, the marriage relationship, and God's design for husband and wife.",
    category: "Life & Relationships",
    verses: [
      { book: "Genesis", chapter: 2, verse: 24 },
      { book: "Ephesians", chapter: 5, verse: 25 },
      { book: "1 Corinthians", chapter: 13, verse: 4 },
      { book: "Proverbs", chapter: 18, verse: 22 },
      { book: "Hebrews", chapter: 13, verse: 4 },
      { book: "Colossians", chapter: 3, verse: 19 },
      { book: "Mark", chapter: 10, verse: 9 },
      { book: "1 Peter", chapter: 3, verse: 7 },
      { book: "Ephesians", chapter: 5, verse: 31 },
      { book: "Proverbs", chapter: 31, verse: 10 },
      { book: "Ecclesiastes", chapter: 4, verse: 9 },
      { book: "Song of Solomon", chapter: 8, verse: 7 },
    ],
    relatedTopics: ["love", "family", "gender-relations", "divorce"],
    faq: [
      { question: "What does the Bible say about marriage?", answer: "The Bible presents marriage as a sacred union ordained by God. Genesis 2:24 says a man shall leave his parents and cleave to his wife. Hebrews 13:4 says marriage is honourable, and Mark 10:9 says what God joins, man should not separate." },
      { question: "What are the roles of husband and wife in marriage?", answer: "Ephesians 5 instructs husbands to love their wives as Christ loved the church, and wives to respect their husbands. Both are called to mutual submission (Ephesians 5:21) and sacrificial love." },
    ],
  },
  {
    name: "Family",
    slug: "family",
    description: "Scriptures about family life, honoring parents, raising children, and household unity.",
    category: "Life & Relationships",
    verses: [
      { book: "Psalms", chapter: 127, verse: 3 },
      { book: "Proverbs", chapter: 22, verse: 6 },
      { book: "Deuteronomy", chapter: 6, verse: 6 },
      { book: "Deuteronomy", chapter: 6, verse: 7 },
      { book: "Ephesians", chapter: 6, verse: 4 },
      { book: "Colossians", chapter: 3, verse: 20 },
      { book: "Exodus", chapter: 20, verse: 12 },
      { book: "Proverbs", chapter: 1, verse: 8 },
      { book: "Joshua", chapter: 24, verse: 15 },
      { book: "Psalms", chapter: 128, verse: 3 },
      { book: "Proverbs", chapter: 17, verse: 6 },
      { book: "Genesis", chapter: 18, verse: 19 },
    ],
    relatedTopics: ["children", "marriage", "love", "leadership"],
    faq: [
      { question: "What does the Bible say about family?", answer: "The Bible places high value on family. Joshua 24:15 declares 'as for me and my house, we will serve the LORD.' Parents are instructed to teach children God's ways (Deuteronomy 6:6-7) and children to honor their parents (Exodus 20:12)." },
      { question: "How should Christian families function?", answer: "Christian families are called to love, teach Scripture to children (Proverbs 22:6), honor parents, and serve God together. Ephesians 6:4 says fathers should bring up children in the nurture and admonition of the Lord." },
    ],
  },
  {
    name: "Children",
    slug: "children",
    description: "Bible verses about children, parenting, and God's view of young ones.",
    category: "Life & Relationships",
    verses: [
      { book: "Psalms", chapter: 127, verse: 3 },
      { book: "Mark", chapter: 10, verse: 14 },
      { book: "Proverbs", chapter: 22, verse: 6 },
      { book: "Ephesians", chapter: 6, verse: 1 },
      { book: "Ephesians", chapter: 6, verse: 4 },
      { book: "Deuteronomy", chapter: 6, verse: 7 },
      { book: "Isaiah", chapter: 54, verse: 13 },
      { book: "Proverbs", chapter: 29, verse: 17 },
      { book: "3 John", chapter: 1, verse: 4 },
      { book: "Colossians", chapter: 3, verse: 20 },
      { book: "Matthew", chapter: 19, verse: 14 },
      { book: "Proverbs", chapter: 13, verse: 24 },
    ],
    relatedTopics: ["family", "love", "patience", "wisdom"],
    faq: [
      { question: "What does the Bible say about raising children?", answer: "Proverbs 22:6 says 'Train up a child in the way he should go: and when he is old, he will not depart from it.' Parents are to teach, discipline with love, and bring children up in the Lord (Ephesians 6:4)." },
      { question: "How does God view children?", answer: "Psalm 127:3 says children are a heritage and reward from the Lord. Jesus welcomed children and said the kingdom of heaven belongs to such as these (Mark 10:14). God values and cares for every child." },
    ],
  },
  {
    name: "Friendship",
    slug: "friendship",
    description: "Verses about friendship, loyal companions, and the value of godly relationships.",
    category: "Life & Relationships",
    verses: [
      { book: "Proverbs", chapter: 17, verse: 17 },
      { book: "Proverbs", chapter: 18, verse: 24 },
      { book: "Ecclesiastes", chapter: 4, verse: 9 },
      { book: "Ecclesiastes", chapter: 4, verse: 10 },
      { book: "John", chapter: 15, verse: 13 },
      { book: "Proverbs", chapter: 27, verse: 17 },
      { book: "1 Thessalonians", chapter: 5, verse: 11 },
      { book: "Proverbs", chapter: 27, verse: 9 },
      { book: "Proverbs", chapter: 13, verse: 20 },
      { book: "Galatians", chapter: 6, verse: 2 },
      { book: "Romans", chapter: 12, verse: 10 },
      { book: "Job", chapter: 6, verse: 14 },
    ],
    relatedTopics: ["love", "kindness", "family", "compassion"],
    faq: [
      { question: "What does the Bible say about friendship?", answer: "Proverbs 17:17 says 'A friend loveth at all times.' Proverbs 27:17 teaches that friends sharpen one another like iron. Jesus called His disciples friends (John 15:15) and modeled sacrificial friendship." },
      { question: "What makes a good friend according to Scripture?", answer: "A good friend is loyal (Proverbs 17:17), honest (Proverbs 27:6), encouraging (1 Thessalonians 5:11), and present in times of need (Ecclesiastes 4:9-10). John 15:13 says the greatest love is laying down one's life for friends." },
    ],
  },
  {
    name: "Leadership",
    slug: "leadership",
    description: "Scriptures about godly leadership, servant leadership, and leading with integrity.",
    category: "Life & Relationships",
    verses: [
      { book: "Proverbs", chapter: 11, verse: 14 },
      { book: "Matthew", chapter: 20, verse: 26 },
      { book: "Joshua", chapter: 1, verse: 9 },
      { book: "1 Timothy", chapter: 3, verse: 1 },
      { book: "1 Timothy", chapter: 3, verse: 2 },
      { book: "Proverbs", chapter: 29, verse: 2 },
      { book: "Mark", chapter: 10, verse: 45 },
      { book: "1 Peter", chapter: 5, verse: 2 },
      { book: "1 Peter", chapter: 5, verse: 3 },
      { book: "Hebrews", chapter: 13, verse: 7 },
      { book: "Proverbs", chapter: 16, verse: 12 },
      { book: "Titus", chapter: 1, verse: 7 },
    ],
    relatedTopics: ["wisdom", "humility", "courage", "work"],
    faq: [
      { question: "What does the Bible say about leadership?", answer: "The Bible teaches servant leadership — Jesus said whoever would be great must be servant of all (Matthew 20:26). Leaders should be blameless, temperate, and examples to others (1 Timothy 3:2, 1 Peter 5:3)." },
      { question: "What qualities should a Christian leader have?", answer: "1 Timothy 3 and Titus 1 list qualities including being blameless, self-controlled, hospitable, apt to teach, not greedy, and having a good reputation. Joshua 1:9 adds courage and faithfulness." },
    ],
  },
  {
    name: "Work",
    slug: "work",
    description: "Bible verses about work, diligence, labor, and working for God's glory.",
    category: "Life & Relationships",
    verses: [
      { book: "Colossians", chapter: 3, verse: 23 },
      { book: "Proverbs", chapter: 12, verse: 11 },
      { book: "2 Thessalonians", chapter: 3, verse: 10 },
      { book: "Proverbs", chapter: 14, verse: 23 },
      { book: "Ecclesiastes", chapter: 9, verse: 10 },
      { book: "Genesis", chapter: 2, verse: 15 },
      { book: "Proverbs", chapter: 16, verse: 3 },
      { book: "Ephesians", chapter: 4, verse: 28 },
      { book: "1 Corinthians", chapter: 10, verse: 31 },
      { book: "Proverbs", chapter: 6, verse: 6 },
      { book: "Colossians", chapter: 3, verse: 24 },
      { book: "1 Timothy", chapter: 5, verse: 8 },
    ],
    relatedTopics: ["leadership", "money", "patience", "strength"],
    faq: [
      { question: "What does the Bible say about work?", answer: "Colossians 3:23 says 'whatsoever ye do, do it heartily, as to the Lord.' The Bible presents work as honorable — God worked in creation (Genesis 2:2) and gave Adam work in the garden (Genesis 2:15). Laziness is condemned." },
      { question: "Should Christians view their work as service to God?", answer: "Yes — Colossians 3:23-24 says to work as unto the Lord, not men, knowing you serve Christ. 1 Corinthians 10:31 says to do all things to the glory of God, including everyday labor." },
    ],
  },
  {
    name: "Money",
    slug: "money",
    description: "Scriptures about money, finances, stewardship, and the dangers of loving wealth.",
    category: "Life & Relationships",
    verses: [
      { book: "1 Timothy", chapter: 6, verse: 10 },
      { book: "Hebrews", chapter: 13, verse: 5 },
      { book: "Matthew", chapter: 6, verse: 24 },
      { book: "Proverbs", chapter: 22, verse: 7 },
      { book: "Ecclesiastes", chapter: 5, verse: 10 },
      { book: "Luke", chapter: 16, verse: 11 },
      { book: "Proverbs", chapter: 13, verse: 11 },
      { book: "Matthew", chapter: 6, verse: 19 },
      { book: "Matthew", chapter: 6, verse: 20 },
      { book: "Proverbs", chapter: 23, verse: 4 },
      { book: "Philippians", chapter: 4, verse: 19 },
      { book: "Malachi", chapter: 3, verse: 10 },
    ],
    relatedTopics: ["generosity", "work", "wealth-and-poverty", "gratitude"],
    faq: [
      { question: "What does the Bible say about money?", answer: "The Bible warns that 'the love of money is the root of all evil' (1 Timothy 6:10) but doesn't condemn money itself. It teaches contentment (Hebrews 13:5), wise stewardship, and not serving money over God (Matthew 6:24)." },
      { question: "How should Christians handle finances?", answer: "Scripture teaches avoiding debt (Proverbs 22:7), being content (Hebrews 13:5), giving generously (2 Corinthians 9:7), saving wisely (Proverbs 13:11), and trusting God to provide (Philippians 4:19)." },
    ],
  },
  {
    name: "Generosity",
    slug: "generosity",
    description: "Verses about giving, generosity, tithing, and blessing others through sharing.",
    category: "Life & Relationships",
    verses: [
      { book: "2 Corinthians", chapter: 9, verse: 7 },
      { book: "Proverbs", chapter: 11, verse: 25 },
      { book: "Luke", chapter: 6, verse: 38 },
      { book: "Acts", chapter: 20, verse: 35 },
      { book: "Proverbs", chapter: 19, verse: 17 },
      { book: "1 Timothy", chapter: 6, verse: 18 },
      { book: "Matthew", chapter: 6, verse: 3 },
      { book: "Matthew", chapter: 6, verse: 4 },
      { book: "Hebrews", chapter: 13, verse: 16 },
      { book: "Proverbs", chapter: 22, verse: 9 },
      { book: "Galatians", chapter: 6, verse: 10 },
      { book: "James", chapter: 2, verse: 15 },
      { book: "James", chapter: 2, verse: 16 },
    ],
    relatedTopics: ["kindness", "money", "compassion", "love"],
    faq: [
      { question: "What does the Bible say about giving?", answer: "2 Corinthians 9:7 says God loves a cheerful giver. Acts 20:35 quotes Jesus: 'It is more blessed to give than to receive.' Luke 6:38 promises that generous giving brings abundant returns." },
      { question: "Should Christians tithe?", answer: "Malachi 3:10 commands bringing tithes to the storehouse. While the New Testament emphasizes cheerful, generous giving rather than a strict percentage (2 Corinthians 9:7), many Christians practice tithing as a starting point for generosity." },
    ],
  },
  {
    name: "Justice",
    slug: "justice",
    description: "Bible passages about justice, fairness, defending the oppressed, and righteous judgment.",
    category: "Life & Relationships",
    verses: [
      { book: "Micah", chapter: 6, verse: 8 },
      { book: "Isaiah", chapter: 1, verse: 17 },
      { book: "Proverbs", chapter: 21, verse: 15 },
      { book: "Psalms", chapter: 82, verse: 3 },
      { book: "Amos", chapter: 5, verse: 24 },
      { book: "Zechariah", chapter: 7, verse: 9 },
      { book: "Proverbs", chapter: 31, verse: 8 },
      { book: "Proverbs", chapter: 31, verse: 9 },
      { book: "Isaiah", chapter: 61, verse: 8 },
      { book: "Psalms", chapter: 37, verse: 28 },
      { book: "Deuteronomy", chapter: 16, verse: 20 },
      { book: "Romans", chapter: 12, verse: 19 },
    ],
    relatedTopics: ["compassion", "leadership", "wisdom", "capital-punishment"],
    faq: [
      { question: "What does the Bible say about justice?", answer: "Micah 6:8 says God requires us 'to do justly, and to love mercy, and to walk humbly with thy God.' The Bible commands defending the poor and oppressed (Psalm 82:3) and letting justice roll like a river (Amos 5:24)." },
      { question: "How should Christians pursue justice?", answer: "Isaiah 1:17 says to 'learn to do well; seek judgment, relieve the oppressed, judge the fatherless, plead for the widow.' Christians are called to speak up for those who cannot speak for themselves (Proverbs 31:8-9)." },
    ],
  },
  {
    name: "Healing",
    slug: "healing",
    description: "Scriptures about healing — physical, emotional, and spiritual restoration from God.",
    category: "Life & Relationships",
    verses: [
      { book: "Jeremiah", chapter: 17, verse: 14 },
      { book: "Psalms", chapter: 147, verse: 3 },
      { book: "Isaiah", chapter: 53, verse: 5 },
      { book: "James", chapter: 5, verse: 14 },
      { book: "James", chapter: 5, verse: 15 },
      { book: "Exodus", chapter: 15, verse: 26 },
      { book: "3 John", chapter: 1, verse: 2 },
      { book: "Psalms", chapter: 103, verse: 3 },
      { book: "Proverbs", chapter: 4, verse: 22 },
      { book: "Matthew", chapter: 9, verse: 35 },
      { book: "1 Peter", chapter: 2, verse: 24 },
      { book: "Malachi", chapter: 4, verse: 2 },
    ],
    relatedTopics: ["prayer", "faith", "comfort", "suffering"],
    faq: [
      { question: "What does the Bible say about healing?", answer: "The Bible describes God as a healer — Exodus 15:26 says 'I am the LORD that healeth thee.' Isaiah 53:5 says 'with his stripes we are healed.' James 5:14-15 instructs the sick to call for prayer from church elders." },
      { question: "Does God still heal today?", answer: "Many Christians believe God still heals based on James 5:14-15 and the testimony of believers. Others note that God's answer may be healing, strength to endure, or ultimate healing in eternity. All agree prayer for the sick is commanded." },
    ],
  },
  {
    name: "Suffering",
    slug: "suffering",
    description: "Verses about suffering, enduring hardship, and finding God's purpose in pain.",
    category: "Life & Relationships",
    verses: [
      { book: "Romans", chapter: 8, verse: 18 },
      { book: "James", chapter: 1, verse: 2 },
      { book: "James", chapter: 1, verse: 3 },
      { book: "1 Peter", chapter: 5, verse: 10 },
      { book: "2 Corinthians", chapter: 4, verse: 17 },
      { book: "Romans", chapter: 5, verse: 3 },
      { book: "Romans", chapter: 5, verse: 4 },
      { book: "Psalms", chapter: 34, verse: 19 },
      { book: "John", chapter: 16, verse: 33 },
      { book: "1 Peter", chapter: 4, verse: 12 },
      { book: "1 Peter", chapter: 4, verse: 13 },
      { book: "2 Timothy", chapter: 3, verse: 12 },
    ],
    relatedTopics: ["comfort", "hope", "strength", "patience"],
    faq: [
      { question: "What does the Bible say about suffering?", answer: "The Bible acknowledges suffering is real but purposeful. Romans 8:18 says present sufferings are not comparable to future glory. James 1:2-3 says trials produce patience. 1 Peter 5:10 promises God will restore after suffering." },
      { question: "Why does God allow suffering?", answer: "Scripture suggests suffering builds character (Romans 5:3-4), teaches dependence on God (2 Corinthians 12:9), and refines faith (1 Peter 1:7). Jesus told followers to expect tribulation but also peace in Him (John 16:33)." },
    ],
  },
  {
    name: "Death",
    slug: "death",
    description: "Bible passages about death, dying, and the Christian hope beyond the grave.",
    category: "Life & Relationships",
    verses: [
      { book: "Psalms", chapter: 23, verse: 4 },
      { book: "John", chapter: 11, verse: 25 },
      { book: "John", chapter: 11, verse: 26 },
      { book: "1 Corinthians", chapter: 15, verse: 55 },
      { book: "Revelation", chapter: 21, verse: 4 },
      { book: "Romans", chapter: 14, verse: 8 },
      { book: "Philippians", chapter: 1, verse: 21 },
      { book: "2 Corinthians", chapter: 5, verse: 8 },
      { book: "1 Thessalonians", chapter: 4, verse: 13 },
      { book: "1 Thessalonians", chapter: 4, verse: 14 },
      { book: "Psalms", chapter: 116, verse: 15 },
      { book: "Isaiah", chapter: 25, verse: 8 },
    ],
    relatedTopics: ["heaven", "eternal-life", "grief", "hope"],
    faq: [
      { question: "What does the Bible say about death?", answer: "The Bible presents death as an enemy conquered by Christ. John 11:25 says 'he that believeth in me, though he were dead, yet shall he live.' 1 Corinthians 15:55 triumphantly asks 'O death, where is thy sting?'" },
      { question: "What happens after death according to the Bible?", answer: "2 Corinthians 5:8 says to be absent from the body is to be present with the Lord. 1 Thessalonians 4:13-14 promises that believers who die will be raised when Christ returns." },
    ],
  },
  {
    name: "Grief",
    slug: "grief",
    description: "Scriptures for times of grief, mourning, loss, and bereavement.",
    category: "Life & Relationships",
    verses: [
      { book: "Matthew", chapter: 5, verse: 4 },
      { book: "Psalms", chapter: 34, verse: 18 },
      { book: "Revelation", chapter: 21, verse: 4 },
      { book: "2 Corinthians", chapter: 1, verse: 3 },
      { book: "2 Corinthians", chapter: 1, verse: 4 },
      { book: "Psalms", chapter: 147, verse: 3 },
      { book: "John", chapter: 14, verse: 1 },
      { book: "Romans", chapter: 8, verse: 28 },
      { book: "Psalms", chapter: 30, verse: 5 },
      { book: "Isaiah", chapter: 41, verse: 10 },
      { book: "Psalms", chapter: 73, verse: 26 },
      { book: "1 Thessalonians", chapter: 4, verse: 13 },
    ],
    relatedTopics: ["comfort", "death", "hope", "peace"],
    faq: [
      { question: "What does the Bible say about grief?", answer: "The Bible validates grief — Jesus himself wept (John 11:35). Matthew 5:4 promises comfort for those who mourn. Psalm 34:18 says God is near to the brokenhearted. Grief is a natural response that God meets with compassion." },
      { question: "How can the Bible help someone who is grieving?", answer: "Scripture offers comfort through God's presence (Psalm 23:4), the promise of reunion (1 Thessalonians 4:13-14), and assurance that sorrow is temporary (Psalm 30:5, Revelation 21:4)." },
    ],
  },
  {
    name: "Anxiety",
    slug: "anxiety",
    description: "Bible verses about anxiety, worry, and finding peace through trust in God.",
    category: "Life & Relationships",
    verses: [
      { book: "Philippians", chapter: 4, verse: 6 },
      { book: "Philippians", chapter: 4, verse: 7 },
      { book: "1 Peter", chapter: 5, verse: 7 },
      { book: "Matthew", chapter: 6, verse: 25 },
      { book: "Matthew", chapter: 6, verse: 34 },
      { book: "Isaiah", chapter: 41, verse: 10 },
      { book: "Psalms", chapter: 94, verse: 19 },
      { book: "John", chapter: 14, verse: 27 },
      { book: "Psalms", chapter: 55, verse: 22 },
      { book: "2 Timothy", chapter: 1, verse: 7 },
      { book: "Proverbs", chapter: 12, verse: 25 },
      { book: "Psalms", chapter: 46, verse: 10 },
    ],
    relatedTopics: ["peace", "fear", "trust-in-god", "prayer"],
    faq: [
      { question: "What does the Bible say about anxiety?", answer: "Philippians 4:6 instructs 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.' 1 Peter 5:7 says to cast all your care upon Him." },
      { question: "How can I overcome worry according to the Bible?", answer: "Jesus said not to worry about tomorrow (Matthew 6:34). The Bible prescribes prayer (Philippians 4:6), casting cares on God (1 Peter 5:7), and focusing on His peace (John 14:27) as remedies for anxiety." },
    ],
  },
  {
    name: "Fear",
    slug: "fear",
    description: "Verses about overcoming fear, trusting God's protection, and finding courage.",
    category: "Life & Relationships",
    verses: [
      { book: "Isaiah", chapter: 41, verse: 10 },
      { book: "2 Timothy", chapter: 1, verse: 7 },
      { book: "Psalms", chapter: 23, verse: 4 },
      { book: "Psalms", chapter: 27, verse: 1 },
      { book: "Joshua", chapter: 1, verse: 9 },
      { book: "Psalms", chapter: 56, verse: 3 },
      { book: "Deuteronomy", chapter: 31, verse: 6 },
      { book: "Psalms", chapter: 34, verse: 4 },
      { book: "1 John", chapter: 4, verse: 18 },
      { book: "Romans", chapter: 8, verse: 15 },
      { book: "Psalms", chapter: 118, verse: 6 },
      { book: "Isaiah", chapter: 43, verse: 1 },
    ],
    relatedTopics: ["courage", "anxiety", "trust-in-god", "peace"],
    faq: [
      { question: "What does the Bible say about fear?", answer: "The command 'fear not' appears throughout Scripture. Isaiah 41:10 says 'Fear thou not; for I am with thee.' 2 Timothy 1:7 says God gives a spirit of power and love, not fear. 1 John 4:18 says perfect love casts out fear." },
      { question: "How can I overcome fear with faith?", answer: "Psalm 56:3 says 'What time I am afraid, I will trust in thee.' Fear is overcome by focusing on God's presence (Deuteronomy 31:6), His power (Isaiah 41:10), and His love (1 John 4:18)." },
    ],
  },
  {
    name: "Anger",
    slug: "anger",
    description: "Scriptures about anger, self-control, and responding with patience rather than wrath.",
    category: "Life & Relationships",
    verses: [
      { book: "James", chapter: 1, verse: 19 },
      { book: "James", chapter: 1, verse: 20 },
      { book: "Proverbs", chapter: 15, verse: 1 },
      { book: "Ephesians", chapter: 4, verse: 26 },
      { book: "Proverbs", chapter: 29, verse: 11 },
      { book: "Psalms", chapter: 37, verse: 8 },
      { book: "Proverbs", chapter: 14, verse: 29 },
      { book: "Colossians", chapter: 3, verse: 8 },
      { book: "Proverbs", chapter: 15, verse: 18 },
      { book: "Ecclesiastes", chapter: 7, verse: 9 },
      { book: "Proverbs", chapter: 16, verse: 32 },
      { book: "Ephesians", chapter: 4, verse: 31 },
    ],
    relatedTopics: ["patience", "peace", "forgiveness", "kindness"],
    faq: [
      { question: "What does the Bible say about anger?", answer: "James 1:19-20 instructs being 'slow to wrath: for the wrath of man worketh not the righteousness of God.' Ephesians 4:26 says 'Be ye angry, and sin not' — anger itself isn't always sinful, but how we respond matters." },
      { question: "How should Christians handle anger?", answer: "Proverbs 15:1 says 'A soft answer turneth away wrath.' The Bible teaches self-control (Proverbs 16:32), not nursing anger (Ephesians 4:26), and putting away all bitterness and wrath (Ephesians 4:31)." },
    ],
  },

  // ===== DIFFICULT & CONTROVERSIAL =====
  {
    name: "Capital Punishment",
    slug: "capital-punishment",
    description: "Bible verses related to capital punishment, the death penalty, and taking human life as judgment.",
    category: "Difficult & Controversial",
    verses: [
      { book: "Genesis", chapter: 9, verse: 6 },
      { book: "Exodus", chapter: 21, verse: 12 },
      { book: "Leviticus", chapter: 24, verse: 17 },
      { book: "Numbers", chapter: 35, verse: 30 },
      { book: "Numbers", chapter: 35, verse: 31 },
      { book: "Deuteronomy", chapter: 19, verse: 11 },
      { book: "Deuteronomy", chapter: 19, verse: 12 },
      { book: "Deuteronomy", chapter: 19, verse: 13 },
      { book: "Romans", chapter: 13, verse: 1 },
      { book: "Romans", chapter: 13, verse: 4 },
      { book: "Matthew", chapter: 5, verse: 38 },
      { book: "Matthew", chapter: 5, verse: 39 },
      { book: "John", chapter: 8, verse: 7 },
      { book: "Romans", chapter: 12, verse: 19 },
      { book: "Ezekiel", chapter: 33, verse: 11 },
    ],
    relatedTopics: ["justice", "forgiveness", "war", "anger"],
    faq: [
      { question: "What does the Bible say about capital punishment?", answer: "The Bible contains both support and challenge to capital punishment. Genesis 9:6 and Old Testament law prescribed death for murder. However, Jesus showed mercy (John 8:7) and taught nonretaliation (Matthew 5:38-39). Christians disagree on how to apply these passages today." },
      { question: "Does the New Testament support the death penalty?", answer: "Romans 13:4 says governing authorities bear the sword as God's servant. However, Jesus intervened against a lawful execution (John 8:7), and the NT emphasizes mercy, forgiveness, and leaving vengeance to God (Romans 12:19)." },
    ],
  },
  {
    name: "Gender Relations",
    slug: "gender-relations",
    description: "Bible passages about gender roles, the relationship between men and women, and equality in Christ.",
    category: "Difficult & Controversial",
    verses: [
      { book: "Genesis", chapter: 2, verse: 18 },
      { book: "Genesis", chapter: 2, verse: 24 },
      { book: "1 Corinthians", chapter: 11, verse: 3 },
      { book: "Ephesians", chapter: 5, verse: 21 },
      { book: "Ephesians", chapter: 5, verse: 22 },
      { book: "Ephesians", chapter: 5, verse: 25 },
      { book: "1 Peter", chapter: 3, verse: 1 },
      { book: "1 Peter", chapter: 3, verse: 7 },
      { book: "Colossians", chapter: 3, verse: 18 },
      { book: "Colossians", chapter: 3, verse: 19 },
      { book: "Titus", chapter: 2, verse: 3 },
      { book: "Titus", chapter: 2, verse: 4 },
      { book: "Titus", chapter: 2, verse: 5 },
      { book: "1 Corinthians", chapter: 14, verse: 34 },
      { book: "1 Corinthians", chapter: 14, verse: 35 },
      { book: "Genesis", chapter: 1, verse: 27 },
      { book: "Galatians", chapter: 3, verse: 28 },
      { book: "Proverbs", chapter: 31, verse: 10 },
    ],
    relatedTopics: ["marriage", "women-in-the-bible", "family", "love"],
    faq: [
      { question: "What does the Bible say about gender roles?", answer: "The Bible presents a range of perspectives. Genesis 1:27 says both male and female are made in God's image. Galatians 3:28 declares equality in Christ. Some passages describe role distinctions in marriage and church (Ephesians 5:22-25, 1 Timothy 2:12), which Christians interpret differently." },
      { question: "Does the Bible teach male headship or equality?", answer: "Both concepts appear in Scripture. 1 Corinthians 11:3 mentions headship, while Galatians 3:28 emphasizes equality in Christ. Ephesians 5:21 calls for mutual submission. Christians hold complementarian and egalitarian views based on how they interpret these passages." },
    ],
  },
  {
    name: "Women in the Bible",
    slug: "women-in-the-bible",
    description: "Scriptures about women, their roles, stories of notable biblical women, and God's view of women.",
    category: "Difficult & Controversial",
    verses: [
      { book: "Proverbs", chapter: 31, verse: 10 },
      { book: "Proverbs", chapter: 31, verse: 25 },
      { book: "Proverbs", chapter: 31, verse: 26 },
      { book: "Proverbs", chapter: 31, verse: 30 },
      { book: "Proverbs", chapter: 31, verse: 31 },
      { book: "Genesis", chapter: 1, verse: 27 },
      { book: "Galatians", chapter: 3, verse: 28 },
      { book: "1 Timothy", chapter: 2, verse: 11 },
      { book: "1 Timothy", chapter: 2, verse: 12 },
      { book: "Ephesians", chapter: 5, verse: 22 },
      { book: "Ephesians", chapter: 5, verse: 25 },
      { book: "Ephesians", chapter: 5, verse: 33 },
      { book: "1 Corinthians", chapter: 11, verse: 3 },
      { book: "Judges", chapter: 4, verse: 4 },
      { book: "Judges", chapter: 4, verse: 9 },
      { book: "Ruth", chapter: 1, verse: 16 },
      { book: "Ruth", chapter: 1, verse: 17 },
      { book: "Esther", chapter: 4, verse: 14 },
      { book: "Acts", chapter: 18, verse: 26 },
    ],
    relatedTopics: ["gender-relations", "marriage", "family", "leadership"],
    faq: [
      { question: "How does the Bible portray women?", answer: "The Bible includes heroic women leaders (Deborah in Judges 4), women of faith (Ruth), courage (Esther), and wisdom (Proverbs 31). Both Genesis 1:27 and Galatians 3:28 affirm women's equal worth before God." },
      { question: "What did Jesus teach about women?", answer: "Jesus elevated women radically for His culture — He taught women (Luke 10:39), spoke to them publicly (John 4), included them in His ministry (Luke 8:1-3), and appeared first to women after resurrection (Mark 16:9)." },
    ],
  },
  {
    name: "Genocide",
    slug: "genocide",
    description: "Difficult Bible passages about the destruction of nations, divine judgment, and violence in the Old Testament.",
    category: "Difficult & Controversial",
    verses: [
      { book: "Deuteronomy", chapter: 7, verse: 1 },
      { book: "Deuteronomy", chapter: 7, verse: 2 },
      { book: "1 Samuel", chapter: 15, verse: 2 },
      { book: "1 Samuel", chapter: 15, verse: 3 },
      { book: "Joshua", chapter: 6, verse: 21 },
      { book: "Joshua", chapter: 10, verse: 40 },
      { book: "Deuteronomy", chapter: 20, verse: 16 },
      { book: "Deuteronomy", chapter: 20, verse: 17 },
      { book: "Deuteronomy", chapter: 20, verse: 18 },
      { book: "Numbers", chapter: 31, verse: 17 },
      { book: "Numbers", chapter: 31, verse: 18 },
      { book: "Psalms", chapter: 137, verse: 9 },
      { book: "Judges", chapter: 21, verse: 10 },
      { book: "Judges", chapter: 21, verse: 11 },
      { book: "Ezekiel", chapter: 9, verse: 5 },
      { book: "Ezekiel", chapter: 9, verse: 6 },
      { book: "Isaiah", chapter: 13, verse: 15 },
      { book: "Isaiah", chapter: 13, verse: 16 },
    ],
    relatedTopics: ["war", "justice", "capital-punishment"],
    faq: [
      { question: "Why does the Old Testament contain accounts of genocide?", answer: "These passages are among the most difficult in Scripture. They describe God commanding the destruction of Canaanite nations. Scholars offer various explanations: divine judgment on extreme wickedness, hyperbolic war language common in ancient Near East, or progressive revelation showing God's fuller character revealed in Christ." },
      { question: "How do Christians reconcile Old Testament violence with Jesus?", answer: "Christians interpret these passages in various ways: some see them as God's specific judgment for specific times, not a model for today. Others emphasize Christ's teaching of enemy-love as God's ultimate revelation. Most agree these texts require honest engagement, not dismissal." },
    ],
  },
  {
    name: "Slavery",
    slug: "slavery",
    description: "Bible passages about slavery, servitude, and the treatment of servants in ancient Israel and the early church.",
    category: "Difficult & Controversial",
    verses: [
      { book: "Exodus", chapter: 21, verse: 2 },
      { book: "Exodus", chapter: 21, verse: 3 },
      { book: "Exodus", chapter: 21, verse: 4 },
      { book: "Exodus", chapter: 21, verse: 5 },
      { book: "Exodus", chapter: 21, verse: 6 },
      { book: "Leviticus", chapter: 25, verse: 44 },
      { book: "Leviticus", chapter: 25, verse: 45 },
      { book: "Leviticus", chapter: 25, verse: 46 },
      { book: "Deuteronomy", chapter: 15, verse: 12 },
      { book: "Deuteronomy", chapter: 15, verse: 13 },
      { book: "Deuteronomy", chapter: 15, verse: 14 },
      { book: "Deuteronomy", chapter: 15, verse: 15 },
      { book: "Ephesians", chapter: 6, verse: 5 },
      { book: "Ephesians", chapter: 6, verse: 9 },
      { book: "Colossians", chapter: 3, verse: 22 },
      { book: "Colossians", chapter: 3, verse: 25 },
      { book: "Philemon", chapter: 1, verse: 15 },
      { book: "Philemon", chapter: 1, verse: 16 },
      { book: "1 Timothy", chapter: 6, verse: 1 },
      { book: "1 Timothy", chapter: 6, verse: 2 },
      { book: "Galatians", chapter: 3, verse: 28 },
      { book: "1 Corinthians", chapter: 7, verse: 21 },
      { book: "1 Corinthians", chapter: 7, verse: 23 },
      { book: "Exodus", chapter: 1, verse: 13 },
      { book: "Exodus", chapter: 1, verse: 14 },
    ],
    relatedTopics: ["justice", "gender-relations", "wealth-and-poverty"],
    faq: [
      { question: "Does the Bible condone slavery?", answer: "The Bible regulated slavery within its ancient context while planting seeds for its abolition. Old Testament law limited terms and protected servants' rights. Paul urged Philemon to receive his slave 'as a brother' (Philemon 16). Galatians 3:28 declares all are one in Christ." },
      { question: "How did Christians historically use the Bible regarding slavery?", answer: "Tragically, some used passages like Ephesians 6:5 to justify slavery. However, abolitionists also used Scripture — particularly Galatians 3:28, Exodus's liberation narrative, and Jesus's teachings on human dignity — to argue against the institution." },
    ],
  },
  {
    name: "War",
    slug: "war",
    description: "Bible verses about war, peace, and whether armed conflict can ever be just.",
    category: "Difficult & Controversial",
    verses: [
      { book: "Ecclesiastes", chapter: 3, verse: 8 },
      { book: "Romans", chapter: 13, verse: 4 },
      { book: "Matthew", chapter: 5, verse: 9 },
      { book: "Psalms", chapter: 46, verse: 9 },
      { book: "Isaiah", chapter: 2, verse: 4 },
      { book: "Exodus", chapter: 15, verse: 3 },
      { book: "Joel", chapter: 3, verse: 9 },
      { book: "Joel", chapter: 3, verse: 10 },
      { book: "Psalms", chapter: 144, verse: 1 },
      { book: "Romans", chapter: 12, verse: 18 },
      { book: "Micah", chapter: 4, verse: 3 },
      { book: "2 Chronicles", chapter: 20, verse: 15 },
    ],
    relatedTopics: ["peace", "justice", "genocide", "capital-punishment"],
    faq: [
      { question: "What does the Bible say about war?", answer: "The Bible contains both warrior imagery and peace ideals. Ecclesiastes 3:8 acknowledges 'a time of war, and a time of peace.' Isaiah 2:4 envisions beating swords into plowshares. Jesus called peacemakers blessed (Matthew 5:9) while acknowledging temporal authorities' sword-bearing role (Romans 13:4)." },
      { question: "Is war ever justified according to Scripture?", answer: "Christians hold pacifist and just-war positions. Pacifists cite Jesus's nonviolence and love-of-enemies teaching. Just-war advocates point to Romans 13, Old Testament wars, and the duty to protect the innocent. Both positions have long biblical and theological traditions." },
    ],
  },
  {
    name: "Divorce",
    slug: "divorce",
    description: "Scriptures about divorce, God's design for marriage permanence, and mercy in broken relationships.",
    category: "Difficult & Controversial",
    verses: [
      { book: "Matthew", chapter: 19, verse: 6 },
      { book: "Matthew", chapter: 5, verse: 32 },
      { book: "Mark", chapter: 10, verse: 9 },
      { book: "Malachi", chapter: 2, verse: 16 },
      { book: "1 Corinthians", chapter: 7, verse: 10 },
      { book: "1 Corinthians", chapter: 7, verse: 11 },
      { book: "1 Corinthians", chapter: 7, verse: 15 },
      { book: "Matthew", chapter: 19, verse: 8 },
      { book: "Matthew", chapter: 19, verse: 9 },
      { book: "Luke", chapter: 16, verse: 18 },
      { book: "Deuteronomy", chapter: 24, verse: 1 },
      { book: "Romans", chapter: 7, verse: 2 },
    ],
    relatedTopics: ["marriage", "forgiveness", "love", "family"],
    faq: [
      { question: "What does the Bible say about divorce?", answer: "Jesus said 'What therefore God hath joined together, let not man put asunder' (Mark 10:9). Malachi 2:16 expresses God's displeasure with divorce. However, Jesus acknowledged an exception for sexual immorality (Matthew 19:9), and Paul allowed separation if an unbelieving spouse departs (1 Corinthians 7:15)." },
      { question: "Can divorced Christians remarry?", answer: "Christians interpret this differently. Matthew 19:9 allows remarriage after divorce for unfaithfulness. 1 Corinthians 7:15 may allow it when abandoned by an unbeliever. Some traditions restrict remarriage entirely. All agree God offers grace and restoration." },
    ],
  },
  {
    name: "Homosexuality",
    slug: "homosexuality",
    description: "Bible passages that address homosexuality, same-sex relationships, and sexual ethics.",
    category: "Difficult & Controversial",
    verses: [
      { book: "Leviticus", chapter: 18, verse: 22 },
      { book: "Leviticus", chapter: 20, verse: 13 },
      { book: "Romans", chapter: 1, verse: 26 },
      { book: "Romans", chapter: 1, verse: 27 },
      { book: "1 Corinthians", chapter: 6, verse: 9 },
      { book: "1 Corinthians", chapter: 6, verse: 10 },
      { book: "1 Timothy", chapter: 1, verse: 10 },
      { book: "Genesis", chapter: 19, verse: 5 },
      { book: "Jude", chapter: 1, verse: 7 },
      { book: "1 Corinthians", chapter: 6, verse: 11 },
      { book: "Matthew", chapter: 19, verse: 4 },
      { book: "Matthew", chapter: 19, verse: 5 },
    ],
    relatedTopics: ["marriage", "love", "gender-relations"],
    faq: [
      { question: "What does the Bible say about homosexuality?", answer: "Several passages address same-sex sexual activity: Leviticus 18:22, Romans 1:26-27, and 1 Corinthians 6:9-10 among others. Christians differ on interpretation — traditionalists see these as prohibiting all same-sex activity, while affirming scholars argue these address specific practices (exploitation, idolatry) rather than committed relationships." },
      { question: "How should Christians approach this topic?", answer: "All major Christian traditions agree on treating every person with dignity and love. The debate centers on whether biblical prohibitions apply to modern committed same-sex relationships or were addressing different cultural practices. Both traditional and affirming Christians base their views on Scripture." },
    ],
  },
  {
    name: "Alcohol",
    slug: "alcohol",
    description: "Bible passages about alcohol, wine, drunkenness, and sobriety.",
    category: "Difficult & Controversial",
    verses: [
      { book: "Proverbs", chapter: 20, verse: 1 },
      { book: "Ephesians", chapter: 5, verse: 18 },
      { book: "Proverbs", chapter: 23, verse: 29 },
      { book: "Proverbs", chapter: 23, verse: 30 },
      { book: "Proverbs", chapter: 23, verse: 31 },
      { book: "1 Timothy", chapter: 5, verse: 23 },
      { book: "John", chapter: 2, verse: 9 },
      { book: "John", chapter: 2, verse: 10 },
      { book: "Isaiah", chapter: 5, verse: 11 },
      { book: "Galatians", chapter: 5, verse: 21 },
      { book: "Romans", chapter: 13, verse: 13 },
      { book: "1 Peter", chapter: 5, verse: 8 },
    ],
    relatedTopics: ["wisdom", "anger", "joy", "peace"],
    faq: [
      { question: "Does the Bible forbid drinking alcohol?", answer: "The Bible does not prohibit all alcohol — Jesus turned water into wine (John 2:9) and Paul recommended wine for Timothy's stomach (1 Timothy 5:23). However, it strongly condemns drunkenness (Ephesians 5:18, Galatians 5:21) and warns about alcohol's dangers (Proverbs 20:1, 23:29-31)." },
      { question: "What is the Christian view on alcohol?", answer: "Christians hold varied views. Some practice total abstinence based on wisdom principles. Others allow moderate consumption. All agree the Bible prohibits drunkenness and that wisdom and self-control should govern decisions about alcohol." },
    ],
  },
  {
    name: "Wealth and Poverty",
    slug: "wealth-and-poverty",
    description: "Scriptures about wealth, poverty, God's concern for the poor, and the responsibilities of the rich.",
    category: "Difficult & Controversial",
    verses: [
      { book: "Proverbs", chapter: 22, verse: 2 },
      { book: "1 Timothy", chapter: 6, verse: 17 },
      { book: "Matthew", chapter: 19, verse: 24 },
      { book: "Proverbs", chapter: 19, verse: 17 },
      { book: "James", chapter: 2, verse: 5 },
      { book: "Luke", chapter: 6, verse: 20 },
      { book: "Proverbs", chapter: 28, verse: 6 },
      { book: "Matthew", chapter: 6, verse: 24 },
      { book: "1 Timothy", chapter: 6, verse: 10 },
      { book: "Proverbs", chapter: 30, verse: 8 },
      { book: "Proverbs", chapter: 30, verse: 9 },
      { book: "Deuteronomy", chapter: 15, verse: 11 },
    ],
    relatedTopics: ["money", "generosity", "justice", "compassion"],
    faq: [
      { question: "What does the Bible say about wealth?", answer: "The Bible presents a nuanced view of wealth. It warns that loving money is the root of all evil (1 Timothy 6:10) and that it's hard for the rich to enter heaven (Matthew 19:24). Yet wealth itself isn't condemned — rather its misuse and the pride it can breed. The rich are instructed to be generous (1 Timothy 6:17-18)." },
      { question: "What does the Bible say about the poor?", answer: "God shows special concern for the poor throughout Scripture. Proverbs 19:17 says lending to the poor is lending to God. James 2:5 says God chose the poor to be rich in faith. Deuteronomy 15:11 commands open-handedness toward the needy." },
    ],
  },
];

export function getTopics(): Topic[] {
  return TOPICS;
}

export function getTopic(slug: string): Topic | undefined {
  return TOPICS.find((t) => t.slug === slug);
}

export function getTopicsByCategory(category: string): Topic[] {
  return TOPICS.filter((t) => t.category === category);
}

export function getPopularTopics(): Topic[] {
  const popularSlugs = [
    "love", "faith", "prayer", "forgiveness", "hope",
    "peace", "strength", "anxiety", "healing", "wisdom",
    "salvation", "marriage",
  ];
  return popularSlugs.map((slug) => TOPICS.find((t) => t.slug === slug)!).filter(Boolean);
}
